/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Administradores: () => import('#controllers/admin/administradores_controller'),
    Aliados: () => import('#controllers/admin/aliados_controller'),
    Encargados: () => import('#controllers/admin/encargados_controller'),
    EstadosAliados: () => import('#controllers/admin/estados_aliados_controller'),
    EstadosCanjes: () => import('#controllers/admin/estados_canjes_controller'),
    EstadosEncargados: () => import('#controllers/admin/estados_encargados_controller'),
    EstadosEntregas: () => import('#controllers/admin/estados_entregas_controller'),
    EstadosMateriales: () => import('#controllers/admin/estados_materiales_controller'),
    EstadosPuntos: () => import('#controllers/admin/estados_puntos_controller'),
    EstadosRecompensas: () => import('#controllers/admin/estados_recompensas_controller'),
    EstadosUsuarios: () => import('#controllers/admin/estados_usuarios_controller'),
    Materiales: () => import('#controllers/admin/materiales_controller'),
    Puntos: () => import('#controllers/admin/puntos_controller'),
    Recompensas: () => import('#controllers/admin/recompensas_controller'),
    Roles: () => import('#controllers/admin/roles_controller'),
    TiposRecompensas: () => import('#controllers/admin/tipos_recompensas_controller'),
    Usuarios: () => import('#controllers/admin/usuarios_controller'),
  },
  aliado: {
    Clasificacion: () => import('#controllers/aliado/clasificacion_controller'),
    EntregasAliado: () => import('#controllers/aliado/entregas_aliado_controller'),
    PerfilAliado: () => import('#controllers/aliado/perfil_aliado_controller'),
  },
  auth: {
    Login: () => import('#controllers/auth/login_controller'),
    RecuperarPasswords: () => import('#controllers/auth/recuperar_passwords_controller'),
    Registros: () => import('#controllers/auth/registros_controller'),
  },
  Chatbot: () => import('#controllers/chatbot_controller'),
  Deteccion: () => import('#controllers/deteccion_controller'),
  encargado: {
    Entregas: () => import('#controllers/encargado/entregas_controller'),
    Notificaciones: () => import('#controllers/encargado/notificaciones_controller'),
    ReservasEncargado: () => import('#controllers/encargado/reservas_encargado_controller'),
    ReservasEncargados: () => import('#controllers/encargado/reservas_encargados_controller'),
  },
  Puntos: () => import('#controllers/puntos_controller'),
  PuntosReciclajes: () => import('#controllers/puntos_reciclajes_controller'),
  usuario: {
    AliadosUsuarios: () => import('#controllers/usuario/aliados_usuarios_controller'),
    Canjes: () => import('#controllers/usuario/canjes_controller'),
    Entregas: () => import('#controllers/usuario/entregas_controller'),
    FotoPerfils: () => import('#controllers/usuario/foto_perfils_controller'),
    NotificacionesUsuario: () => import('#controllers/usuario/notificaciones_usuario_controller'),
    Perfil: () => import('#controllers/usuario/perfil_controller'),
    Puntos: () => import('#controllers/usuario/puntos_controller'),
    Recompensas: () => import('#controllers/usuario/recompensas_controller'),
    ReservasUsuario: () => import('#controllers/usuario/reservas_usuario_controller'),
    ReservasUsuarios: () => import('#controllers/usuario/reservas_usuarios_controller'),
  },
}
